"""
Django settings for django_decoupled project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
# pylint: disable=R0801
# mypy: ignore-errors
from typing import List

from .base import *  # pylint: disable=W0401,W0614

# https://docs.djangoproject.com/en/dev/ref/settings/#debug
DEBUG = False

SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# TODO: Change this to the production host when it is ready.  # pylint: disable=W0511
ALLOWED_HOSTS: List[str] = [".clasifica.io.localhost"]
CSRF_TRUSTED_ORIGINS = ["https://*.clasifica.io.localhost"]

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.environ["PG_NAME"],
        "USER": os.environ["PG_USER"],
        "PASSWORD": os.environ["PG_PASSWORD"],
        "HOST": os.environ["PG_HOST"],
        "PORT": os.environ["PG_PORT"],
    }
}

STATIC_ROOT = BASE_DIR / "staticfiles"
