# Generated by Django 4.2.1 on 2023-05-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_workspace_model_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="metrics",
            field=models.JSONField(blank=True, default=dict, verbose_name="metrics"),
        ),
    ]
