# Generated by Django 4.2.1 on 2023-05-26 07:41
"""Migration for altering document text field."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration for altering document text field."""

    dependencies = [
        ("workspaces", "0004_alter_workspace_metrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="text",
            field=models.CharField(max_length=2000, verbose_name="text"),
        ),
    ]
