# Generated by Django 4.1.7 on 2023-04-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="model_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="model_id"
            ),
        ),
    ]
