# Generated by Django 4.2.1 on 2023-05-26 14:34
"""Migrations for the workspaces app."""
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration class."""

    dependencies = [
        ("workspaces", "0005_alter_document_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="text",
            field=models.TextField(verbose_name="text"),
        ),
    ]
